version: "3.9"
services:

  client:
    container_name: gi_dev_test_client_container
    build: ./client
    # volumes:
    #   - ./client:/client
    # image: vep_client_container_image
    depends_on:
      - server
    ports:
      - 8000:8000
    # stdin_open: true
    # tty: true
    # command: http-server dist
  
  server:
    container_name: gi_dev_test_server_container
    build: ./server
    restart: always
    # volumes:
    #   - ..:/server:cached
    depends_on:
      - db
    ports:
      - 5000:5000
    # stdin_open: true
    # tty: true
    # command: yarn start
    # network_mode: service:db

  db:
    container_name: gi_dev_test_db_container
    image: postgres:latest
    restart: always
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    # volumes:
    #   - ./db:/var/lib/postgresql/data

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

# volumes:
#   db:
  
  # server:
  #   container_name: vep_server_container
  #   build: ./docker/server
  #   image: vep_server_container_image
  #   depends_on:
  #     - db
  #   ports:
  #     - "3000:3000"
  #   command: sleep infinity
  #   network_mode: service:db
    # command: yarn start
    # environment:
    #   DATABASE_URL: db://postgres:postgres@db:5432/postgres
    #   NODE_ENV: development
    #   PORT: 3000
  
  # db:
  #   container_name: vep_db_container
  #   # build: ./docker/db
  #   image: postgres:latest
  #   # ports:
  #   #   - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres

# volumes:
#   postgres-data: